export {
  type DetectedFramework,
  type FrameworkCategory,
  type DocSection,
  type DocTreeIndex,
  type MonorepoModule,
  type ProjectStack,
  type MonorepoConfig,
  type FrameworkMeta,
  type VersionedMeta,
  type FrameworkDocEntry,
  FRAMEWORK_DOCS,
  resolveFrameworkMeta,
  parseMajor,
} from './types/index.js';
